/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import creacionales.abstractFactory.Catalogo;
import estructurales.decorator.Vendible;
import javax.swing.JOptionPane;


/**
 *
 * @author sebas
 */
public class FrameIndividual extends javax.swing.JFrame {

    public FrameIndividual() {
        initComponents();
        setLocationRelativeTo(null);
        this.GroupVehiculo.add(this.BtnElectrico);
        this.GroupVehiculo.add(this.BtnGasolina);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupVehiculo = new javax.swing.ButtonGroup();
        LblTxt1 = new javax.swing.JLabel();
        LblTxt2 = new javax.swing.JLabel();
        BtnElectrico = new javax.swing.JRadioButton();
        BtnGasolina = new javax.swing.JRadioButton();
        BtnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTxt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTxt1.setText("Solicitud Cliente:");

        LblTxt2.setText("Desea solicitar vehiculos eléctricos o de gasolina:");

        BtnElectrico.setText("Eléctricos");

        BtnGasolina.setText("Gasolina");

        BtnSeleccionar.setText("Seleccionar");
        BtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(BtnElectrico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnGasolina)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(BtnSeleccionar)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LblTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LblTxt2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnElectrico)
                    .addComponent(BtnGasolina))
                .addGap(18, 18, 18)
                .addComponent(BtnSeleccionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSeleccionarActionPerformed
          
          if(this.BtnElectrico.isSelected()){
              String selec = this.BtnElectrico.getText();
              JOptionPane.showMessageDialog(null,"Usted ha seleccionado: "+selec,"Mensaje", 1);
              FrameCatalogoUsuario e = new FrameCatalogoUsuario(selec);
              e.setVisible(true);
              dispose();
          }
          else{
              if(this.BtnGasolina.isSelected()){
                  String selec = this.BtnGasolina.getText();
                  JOptionPane.showMessageDialog(null,"Usted ha seleccionado: "+selec,"Mensaje", 1);
                  FrameCatalogoUsuario e = new FrameCatalogoUsuario(selec);
                  e.setVisible(true);
                  dispose();
              }
          }
          
    }//GEN-LAST:event_BtnSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameIndividual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BtnElectrico;
    private javax.swing.JRadioButton BtnGasolina;
    private javax.swing.JButton BtnSeleccionar;
    private javax.swing.ButtonGroup GroupVehiculo;
    private javax.swing.JLabel LblTxt1;
    private javax.swing.JLabel LblTxt2;
    // End of variables declaration//GEN-END:variables
}
